import type { Metadata } from "next";

import "@/styles/globals.css";
import SideBar from "@/components/SideBar";
import ClientSideBar from "@/components/ClientSideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <ClientSideBar></ClientSideBar>
      <body>
        {children}
      </body>
    </html>
  );
}
