import type { Metadata } from "next";

import "@/styles/globals.css";
import SideBar from "@/components/SideNav/SideNav";
import ClientSideNav from "@/components/SideNav/ClientSideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html>
      <body className="horizontal-flex">
        <div>
          <ClientSideNav />
        </div>
        <div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
